### ISSUE TITLE
hector_quadrotor_description" does not exist.

### ISSUE THREAD

**Issue by TS-YinJie** [tahsinkose/hector-moveit#3]
Thanks for your helpful answer!
Now I install the gazebo9, and I met a new error again:

Errors     << hector_quadrotor_description:check /home/yinjie/ws_moveit/logs/hector_quadrotor_description/build.check.008.log
CMake Error: The source directory "/home/yinjie/ws_moveit/src/hector_quadrotor-kinetic-devel/hector_quadrotor_description" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** [cmake_check_build_system] Error 1

and 

Could not find a package configuration file provided by
  "hector_pose_estimation" with any of the following names:

    hector_pose_estimationConfig.cmake
    hector_pose_estimation-config.cmake

  Add the installation prefix of "hector_pose_estimation" to
  CMAKE_PREFIX_PATH or set "hector_pose_estimation_DIR" to a directory
  containing one of the above files.  If "hector_pose_estimation" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)

Can I ask a more question? why are the directory hector_gazebo and hector_gazebo empty?

**Comment by tahsinkose** [comment]
>  Can I ask a more question? why are the directory hector_gazebo and hector_gazebo empty?

Let me start with your last question. When cloning a repository with submodules, you should run the command `git clone --recurse-submodules <repo_url.git> `. Otherwise, those directories will be downloaded empty to your local. Since I will not do any implementation on those packages, I have made them submodules. 

I recommend you to have a clean clone as I suggested. It should solve your actual problem, too.

**Comment by tahsinkose** [comment]
I'm deprecating this issue because of one month inactivity.
